### PR TITLE
Managment offset in ZooKeeper

### PR DESCRIPTION
**Pull request by t-kitamura**
Hi @htgc ,

I want to retry to pull message, when failed to emit record in in-plugin.
So, I implemented the option as follows.

1. When succeeded to emit process, the offset is saved in zookeeper.
1. When failed to emit process, the offset is not saved in zookeeper.
1. And retry to pull the message of finally saved offset.

I implemented it to set as follows.
```XML
<source>
  type                  kafka
  host                  127.0.0.1
  port                  9092
  topics                topic1,topic2  
  format                text
  offset_zookeeper      127.0.0.1:2181 ... zookeeper host and port.
  offset_zk_root_node   /fluent/kafka ... zookeeper root node for saving offsets.
</source>
```
When set 'offset_zookeeper', enable this function.

Please check this reqeust.

### CODE REVIEW

**Comment by t-kitamura** [comment]
Hi @htgc ,
この機能をリリースしてもらうことはできませんか？

**Comment by t-kitamura** [comment]
Hi @htgc ,
Please release this feature.
Is it possible?

**Comment by htgc** [comment]
Hello @t-kitamura,
Sorry for inconvenience.
I have just released as v0.0.18.
Thanks,

**Comment by t-kitamura** [comment]
Hi @htgc , 
Thank you!

**Pull request merged**
