### PR TITLE
Assign offset to each topic.

### PR DESCRIPTION
**Pull request by t-kitamura**
Hi @htgc ,

I want to assign offset to each topic in in-plugin.
Because, I want to start processing from the assigned offset for specific topics.
I implemented it to set as follows.

```XML
<source>
        type                    kafka
        host                    127.0.0.1
        port                    9092
        format                  text
        <topic>
                topic           topic1
                partition       0
                offset          -1
        </topic>
        <topic>
                topic           topic2
                partition       0
                offset          5
        </topic>
</source>
```

Please check this request.

### CODE REVIEW

**Comment by htgc** [comment]
Thank you for your contribution!
Could you update README for input plugin as well?

**Comment by t-kitamura** [comment]
OK.
I will update README.

**Comment by t-kitamura** [comment]
Hi @htgc ,
I updated README.
Please check it.

**Comment by htgc** [comment]
Thanks!

**Pull request merged**
