### PR TITLE
Add offset info in record.

### PR DESCRIPTION
**Pull request by t-kitamura**
Hi @htgc ,

I want to add offset info in record.
Because, I want to perform re-try with appointed offset when I fail in the middle of streaming processing.
To do so, I need to know the offset of message which processed the record.

Please check this request.

### CODE REVIEW

**Comment by htgc** [comment]
Thank you for your contribution! Unfortunately, it's conflicted by another commit. Could you rebase it? Thanks,

**Comment by t-kitamura** [comment]
Hi @htgc ,

I merged lastest master.
And, I rebased commit.

Please check it.

**Comment by htgc** [comment]
Released. Thanks again!

**Comment by vnnw** [comment]
Hi, @t-kitamura 

Seems AddOffsetInRecord does not work for group consumer. Care to add it for group consumer?

**Pull request merged**
